workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "com.yourcompany.airport"
      node: 18.17.0
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Setup React Native iOS
        script: |
          # Generate iOS files if they don't exist
          if [ ! -d "ios" ]; then
            echo "Generating iOS platform for React Native..."
            npx @react-native-community/cli@latest init-ios --skip-install
          fi
          
          # Ensure we have the right structure
          ls -la ios/ || echo "iOS folder contents:"
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build for iOS Simulator
        script: |
          npx react-native build-ios --mode Debug --simulator
    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/*.app
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: false
