workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "Airport.xcworkspace"
        XCODE_SCHEME: "Airport"
        BUNDLE_ID: "com.yourcompany.airport"
      node: 18.17.0
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build for iOS Simulator
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --destination "generic/platform=iOS Simulator" \
            --archive-flags "-sdk iphonesimulator"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.app
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: false
